name: react-workflow

on:
  push:
    branches: "*"
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pro-tasker

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v23.7.0
      - name: install dependencies
        run: npm ci
      # - name: run lint
      #   run: npm run lint
      # - name: run tests
      #   run: npm run test
      - name: builds project
        run: npm run build
